---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gogs-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/gogs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi